[package]
name = "checksum"
version = "0.1.0"
authors = ["Leigh McCulloch <leigh@mcchouse.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.5"
hex-literal = "0.3.1"
